# Imports
from tkinter import *
import json

# Data
d = open('data.json')
data = json.load(d)
d.close()


def button_clicked():
    print(int(product_06.get())*5)
    # something = int(product_06.get()) * int(product_16.get())
    # hey_now = int(new_input.get()) * 1.609
    # my_label3["text"] = hey_now


# UI/Tkinter Config
window = Tk()

window.title("KIV Use Calculator")
window.config(bg="white", padx=20, pady=20, width=200, height=200)

# Super Header
oil_on_hand = Label(text="KIV on hand: ", bg="white", highlightthickness=0)
oil_on_hand.grid(column=0, row=0, sticky="E")

# calc button
button = Button(text="Calculate", command=button_clicked)
button.grid(column=10, row=0)


# Header Row
header_0 = Label(text="Product", bg="white", highlightthickness=0)
header_0.grid(column=0, row=1, sticky="E")
header_1 = Label(text="COGS", bg="white", highlightthickness=0)
header_1.grid(column=1, row=1, sticky="E")
header_2 = Label(text="Price", bg="white", highlightthickness=0)
header_2.grid(column=2, row=1, sticky="E")
header_3 = Label(text="KIV/Unit", bg="white", highlightthickness=0)
header_3.grid(column=3, row=1, sticky="E")
# Commented out for simplicity of concept, as this is for ONE Key Input Variable not two
# header_4 = Label(text="KIV Category", bg="white", highlightthickness=0)
# header_4.grid(column=4, row=1, sticky="E")
# header_5 = Label(text="Adjusted KIV per Unit", bg="white", highlightthickness=0)
# header_5.grid(column=5, row=1, sticky="E")
header_6 = Label(text="Amount Desired (AD)", bg="white", highlightthickness=0)
header_6.grid(column=6, row=1, sticky="E")
header_7 = Label(text="KIV Consumed", bg="white", highlightthickness=0)
header_7.grid(column=7, row=1, sticky="E")
header_8 = Label(text="Total Sales on AD", bg="white", highlightthickness=0)
header_8.grid(column=8, row=1, sticky="E")
header_9 = Label(text="COGs on AD", bg="white", highlightthickness=0)
header_9.grid(column=9, row=1, sticky="E")
header_10 = Label(text="$/KIV/Unit", bg="white", highlightthickness=0)
header_10.grid(column=10, row=1, sticky="E")

# Product Name Imports
product_0 = Label(text=f"{data[0]['product']}", bg="white", highlightthickness=0)
product_0.grid(column=0, row=2, sticky="E")
product_1 = Label(text=f"{data[1]['product']}", bg="white", highlightthickness=0)
product_1.grid(column=0, row=3, sticky="E")
product_2 = Label(text=f"{data[2]['product']}", bg="white", highlightthickness=0)
product_2.grid(column=0, row=4, sticky="E")
product_3 = Label(text=f"{data[3]['product']}", bg="white", highlightthickness=0)
product_3.grid(column=0, row=5, sticky="E")
product_4 = Label(text=f"{data[4]['product']}", bg="white", highlightthickness=0)
product_4.grid(column=0, row=6, sticky="E")
product_5 = Label(text=f"{data[5]['product']}", bg="white", highlightthickness=0)
product_5.grid(column=0, row=7, sticky="E")
product_6 = Label(text=f"{data[6]['product']}", bg="white", highlightthickness=0)
product_6.grid(column=0, row=8, sticky="E")
product_7 = Label(text=f"{data[7]['product']}", bg="white", highlightthickness=0)
product_7.grid(column=0, row=9, sticky="E")
product_8 = Label(text=f"{data[8]['product']}", bg="white", highlightthickness=0)
product_8.grid(column=0, row=10, sticky="E")
product_9 = Label(text=f"{data[9]['product']}", bg="white", highlightthickness=0)
product_9.grid(column=0, row=11, sticky="E")
product_10 = Label(text=f"{data[10]['product']}", bg="white", highlightthickness=0)
product_10.grid(column=0, row=12, sticky="E")
product_11 = Label(text=f"{data[11]['product']}", bg="white", highlightthickness=0)
product_11.grid(column=0, row=13, sticky="E")
product_12 = Label(text=f"{data[12]['product']}", bg="white", highlightthickness=0)
product_12.grid(column=0, row=14, sticky="E")

# COGs Imports
product_01 = Label(text=f"{data[0]['cogs']}", bg="white", highlightthickness=0)
product_01.grid(column=1, row=2, sticky="E")
product_11 = Label(text=f"{data[1]['cogs']}", bg="white", highlightthickness=0)
product_11.grid(column=1, row=3, sticky="E")
product_21 = Label(text=f"{data[2]['cogs']}", bg="white", highlightthickness=0)
product_21.grid(column=1, row=4, sticky="E")
product_31 = Label(text=f"{data[3]['cogs']}", bg="white", highlightthickness=0)
product_31.grid(column=1, row=5, sticky="E")
product_41 = Label(text=f"{data[4]['cogs']}", bg="white", highlightthickness=0)
product_41.grid(column=1, row=6, sticky="E")
product_51 = Label(text=f"{data[5]['cogs']}", bg="white", highlightthickness=0)
product_51.grid(column=1, row=7, sticky="E")
product_61 = Label(text=f"{data[6]['cogs']}", bg="white", highlightthickness=0)
product_61.grid(column=1, row=8, sticky="E")
product_71 = Label(text=f"{data[7]['cogs']}", bg="white", highlightthickness=0)
product_71.grid(column=1, row=9, sticky="E")
product_81 = Label(text=f"{data[8]['cogs']}", bg="white", highlightthickness=0)
product_81.grid(column=1, row=10, sticky="E")
product_91 = Label(text=f"{data[9]['cogs']}", bg="white", highlightthickness=0)
product_91.grid(column=1, row=11, sticky="E")
product_101 = Label(text=f"{data[10]['cogs']}", bg="white", highlightthickness=0)
product_101.grid(column=1, row=12, sticky="E")
product_111 = Label(text=f"{data[11]['cogs']}", bg="white", highlightthickness=0)
product_111.grid(column=1, row=13, sticky="E")
product_121 = Label(text=f"{data[12]['cogs']}", bg="white", highlightthickness=0)
product_121.grid(column=1, row=14, sticky="E")

# Price Imports
product_02 = Label(text=f"{data[0]['wholesale_price']}", bg="white", highlightthickness=0)
product_02.grid(column=2, row=2, sticky="E")
product_12 = Label(text=f"{data[1]['wholesale_price']}", bg="white", highlightthickness=0)
product_12.grid(column=2, row=3, sticky="E")
product_22 = Label(text=f"{data[2]['wholesale_price']}", bg="white", highlightthickness=0)
product_22.grid(column=2, row=4, sticky="E")
product_32 = Label(text=f"{data[3]['wholesale_price']}", bg="white", highlightthickness=0)
product_32.grid(column=2, row=5, sticky="E")
product_42 = Label(text=f"{data[4]['wholesale_price']}", bg="white", highlightthickness=0)
product_42.grid(column=2, row=6, sticky="E")
product_52 = Label(text=f"{data[5]['wholesale_price']}", bg="white", highlightthickness=0)
product_52.grid(column=2, row=7, sticky="E")
product_62 = Label(text=f"{data[6]['wholesale_price']}", bg="white", highlightthickness=0)
product_62.grid(column=2, row=8, sticky="E")
product_72 = Label(text=f"{data[7]['wholesale_price']}", bg="white", highlightthickness=0)
product_72.grid(column=2, row=9, sticky="E")
product_82 = Label(text=f"{data[8]['wholesale_price']}", bg="white", highlightthickness=0)
product_82.grid(column=2, row=10, sticky="E")
product_92 = Label(text=f"{data[9]['wholesale_price']}", bg="white", highlightthickness=0)
product_92.grid(column=2, row=11, sticky="E")
product_102 = Label(text=f"{data[10]['wholesale_price']}", bg="white", highlightthickness=0)
product_102.grid(column=2, row=12, sticky="E")
product_112 = Label(text=f"{data[11]['wholesale_price']}", bg="white", highlightthickness=0)
product_112.grid(column=2, row=13, sticky="E")
product_122 = Label(text=f"{data[12]['wholesale_price']}", bg="white", highlightthickness=0)
product_122.grid(column=2, row=14, sticky="E")

# KIV/Unit
product_03 = Label(text=f"{data[0]['kiv_per_unit']}", bg="white", highlightthickness=0)
product_03.grid(column=3, row=2, sticky="E")
product_13 = Label(text=f"{data[1]['kiv_per_unit']}", bg="white", highlightthickness=0)
product_13.grid(column=3, row=3, sticky="E")
product_23 = Label(text=f"{data[2]['kiv_per_unit']}", bg="white", highlightthickness=0)
product_23.grid(column=3, row=4, sticky="E")
product_33 = Label(text=f"{data[3]['kiv_per_unit']}", bg="white", highlightthickness=0)
product_33.grid(column=3, row=5, sticky="E")
product_43 = Label(text=f"{data[4]['kiv_per_unit']}", bg="white", highlightthickness=0)
product_43.grid(column=3, row=6, sticky="E")
product_53 = Label(text=f"{data[5]['kiv_per_unit']}", bg="white", highlightthickness=0)
product_53.grid(column=3, row=7, sticky="E")
product_63 = Label(text=f"{data[6]['kiv_per_unit']}", bg="white", highlightthickness=0)
product_63.grid(column=3, row=8, sticky="E")
product_73 = Label(text=f"{data[7]['kiv_per_unit']}", bg="white", highlightthickness=0)
product_73.grid(column=3, row=9, sticky="E")
product_83 = Label(text=f"{data[8]['kiv_per_unit']}", bg="white", highlightthickness=0)
product_83.grid(column=3, row=10, sticky="E")
product_93 = Label(text=f"{data[9]['kiv_per_unit']}", bg="white", highlightthickness=0)
product_93.grid(column=3, row=11, sticky="E")
product_103 = Label(text=f"{data[10]['kiv_per_unit']}", bg="white", highlightthickness=0)
product_103.grid(column=3, row=12, sticky="E")
product_113 = Label(text=f"{data[11]['kiv_per_unit']}", bg="white", highlightthickness=0)
product_113.grid(column=3, row=13, sticky="E")
product_123 = Label(text=f"{data[12]['kiv_per_unit']}", bg="white", highlightthickness=0)
product_123.grid(column=3, row=14, sticky="E")

# Product Name Imports
product_06 = Entry(bg="white", highlightthickness=0)
product_06.grid(column=6, row=2, sticky="E")
product_16 = Entry(bg="white", highlightthickness=0)
product_16.grid(column=6, row=3, sticky="E")
product_26 = Entry(bg="white", highlightthickness=0)
product_26.grid(column=6, row=4, sticky="E")
product_36 = Entry(bg="white", highlightthickness=0)
product_36.grid(column=6, row=5, sticky="E")
product_46 = Entry(bg="white", highlightthickness=0)
product_46.grid(column=6, row=6, sticky="E")
product_56 = Entry(bg="white", highlightthickness=0)
product_56.grid(column=6, row=7, sticky="E")
product_66 = Entry(bg="white", highlightthickness=0)
product_66.grid(column=6, row=8, sticky="E")
product_76 = Entry(bg="white", highlightthickness=0)
product_76.grid(column=6, row=9, sticky="E")
product_86 = Entry(bg="white", highlightthickness=0)
product_86.grid(column=6, row=10, sticky="E")
product_96 = Entry(bg="white", highlightthickness=0)
product_96.grid(column=6, row=11, sticky="E")
product_106 = Entry(bg="white", highlightthickness=0)
product_106.grid(column=6, row=12, sticky="E")
product_116 = Entry(bg="white", highlightthickness=0)
product_116.grid(column=6, row=13, sticky="E")
product_126 = Entry(bg="white", highlightthickness=0)
product_126.grid(column=6, row=14, sticky="E")

# KIV Consumed
product_07 = Label(bg="white", highlightthickness=0)
product_07.grid(column=6, row=2, sticky="E")
product_17 = Label(bg="white", highlightthickness=0)
product_17.grid(column=6, row=3, sticky="E")
product_27 = Label(bg="white", highlightthickness=0)
product_27.grid(column=6, row=4, sticky="E")
product_37 = Label(bg="white", highlightthickness=0)
product_37.grid(column=6, row=5, sticky="E")
product_47 = Label(bg="white", highlightthickness=0)
product_47.grid(column=6, row=6, sticky="E")
product_57 = Label(bg="white", highlightthickness=0)
product_57.grid(column=6, row=7, sticky="E")
product_67 = Label(bg="white", highlightthickness=0)
product_67.grid(column=6, row=8, sticky="E")
product_77 = Label(bg="white", highlightthickness=0)
product_77.grid(column=6, row=9, sticky="E")
product_87 = Label(bg="white", highlightthickness=0)
product_87.grid(column=6, row=10, sticky="E")
product_97 = Label(bg="white", highlightthickness=0)
product_97.grid(column=6, row=11, sticky="E")
product_107 = Label(bg="white", highlightthickness=0)
product_107.grid(column=6, row=12, sticky="E")
product_117 = Label(bg="white", highlightthickness=0)
product_117.grid(column=6, row=13, sticky="E")
product_127 = Label(bg="white", highlightthickness=0)
product_127.grid(column=6, row=14, sticky="E")


window.mainloop()
